### ISSUE TITLE
Stripe bump

### ISSUE THREAD

**Issue by ghenry** [bfontaine/homebrew-utils#5]
Hi Baptiste,

Any chance you could bump your Stripe formula to v1.8.0?

Using it on Linux as per https://github.com/stripe/stripe-cli/issues/645#issuecomment-903971917 

Thanks for creating this.

Gavin.

**Comment by bfontaine** [comment]
Done.

**Comment by ghenry** [comment]
New one again :-)

A newer version of the Stripe CLI is available, please update to: v1.8.1

**Comment by ghenry** [comment]
nm, I see that's what you've already done!
